# Generated by Django 4.1.7 on 2023-04-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic.png', upload_to=''),
        ),
    ]
