# Generated by Django 4.1.7 on 2023-06-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
