# Generated by Django 4.1.7 on 2023-06-12 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0008_post_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voters',
            field=models.ManyToManyField(related_name='voted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
